name: Backend CI - Build & Push to ECR

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::215572308714:role/GitHubActions-ECR
          aws-region: ap-southeast-2

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image (backend only)
        run: |
          docker build -t devconnect-backend ./back-end

      - name: Tag Docker image
        run: |
          docker tag devconnect-backend:latest 215572308714.dkr.ecr.ap-southeast-2.amazonaws.com/devconnect-backend:latest

      - name: Push Docker image to ECR
        run: |
          docker push 215572308714.dkr.ecr.ap-southeast-2.amazonaws.com/devconnect-backend:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 13.211.197.100
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1. Login to ECR (Refresh token)
            aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 215572308714.dkr.ecr.ap-southeast-2.amazonaws.com

            # 2. Pull the latest image
            docker pull 215572308714.dkr.ecr.ap-southeast-2.amazonaws.com/devconnect-backend:latest

            # 3. Stop & Remove existing container
            docker stop devconnect-backend || true
            docker rm devconnect-backend || true

            # 4. Run new container
            docker run -d --name devconnect-backend -p 5000:5000 --env-file .env 215572308714.dkr.ecr.ap-southeast-2.amazonaws.com/devconnect-backend:latest

            # 5. Verify deployment
            docker ps
